<?php

namespace App\Http\Controllers\Instructor;

use App\Http\Controllers\Controller;
use App\Models\Level;
use App\Models\SourceCode;
use App\Models\SourceCodeCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SourceCodeController extends Controller
{
    public function index(Request $request)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can see all source codes, instructor only sees their own
        $query = $user->isAdmin() 
            ? SourceCode::with(['category', 'level'])
            : SourceCode::where('instructor_id', $userId)->with(['category', 'level']);

        // Search
        if ($request->has('search') && $request->search) {
            $query->where(function($q) use ($request) {
                $q->where('title', 'like', "%{$request->search}%")
                  ->orWhere('subtitle', 'like', "%{$request->search}%");
            });
        }

        // Filter by status
        if ($request->has('status') && $request->status) {
            if ($request->status === 'published') {
                $query->where('is_published', true);
            } else {
                $query->where('is_published', false);
            }
        }

        $sourceCodes = $query->latest()->paginate(12);

        // If AJAX request, return only the table HTML
        if ($request->ajax()) {
            return response()->json([
                'html' => view('instructor.source-codes.index', compact('sourceCodes'))->render()
            ]);
        }

        return view('instructor.source-codes.index', compact('sourceCodes'));
    }

    public function create()
    {
        $categories = SourceCodeCategory::all();
        $levels = Level::orderBy('order')->get();
        
        return view('instructor.source-codes.create', compact('categories', 'levels'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'subtitle' => 'nullable|string|max:255',
            'thumbnail' => 'nullable|image|max:2048',
            'source_code_category_id' => 'required|exists:source_code_categories,id',
            'level_id' => 'required|exists:levels,id',
            'description' => 'required|string',
            'price' => 'required|numeric|min:0',
            'github_url' => 'nullable|url',
            'demo_url' => 'nullable|url',
            'technologies' => 'nullable|string',
            'download_url' => 'nullable|url',
        ]);

        if ($request->hasFile('thumbnail')) {
            $validated['thumbnail'] = $request->file('thumbnail')->store('source-codes/thumbnails', 'public');
        }

        // Convert technologies string to array
        if (!empty($validated['technologies'])) {
            $validated['technologies'] = array_map('trim', explode(',', $validated['technologies']));
        } else {
            $validated['technologies'] = [];
        }

        $validated['instructor_id'] = Auth::id();
        // Slug will be auto-generated by model boot method

        $sourceCode = SourceCode::create($validated);

        return redirect()->route('instructor.source-codes.show', $sourceCode->id)
            ->with('success', 'Source code berhasil dibuat!');
    }

    public function show($id)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can see all source codes, instructor only sees their own
        $query = $user->isAdmin()
            ? SourceCode::with(['category', 'level'])
            : SourceCode::where('instructor_id', $userId)->with(['category', 'level']);
        
        $sourceCode = $query->findOrFail($id);

        return view('instructor.source-codes.show', compact('sourceCode'));
    }

    public function edit($id)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can edit all source codes, instructor only edits their own
        $query = $user->isAdmin()
            ? SourceCode::query()
            : SourceCode::where('instructor_id', $userId);
        
        $sourceCode = $query->findOrFail($id);
        $categories = SourceCodeCategory::all();
        $levels = Level::orderBy('order')->get();

        return view('instructor.source-codes.edit', compact('sourceCode', 'categories', 'levels'));
    }

    public function update(Request $request, $id)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can update all source codes, instructor only updates their own
        $query = $user->isAdmin()
            ? SourceCode::query()
            : SourceCode::where('instructor_id', $userId);
        
        $sourceCode = $query->findOrFail($id);

        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'subtitle' => 'nullable|string|max:255',
            'thumbnail' => 'nullable|image|max:2048',
            'source_code_category_id' => 'required|exists:source_code_categories,id',
            'level_id' => 'required|exists:levels,id',
            'description' => 'required|string',
            'price' => 'required|numeric|min:0',
            'github_url' => 'nullable|url',
            'demo_url' => 'nullable|url',
            'technologies' => 'nullable|string',
            'download_url' => 'nullable|url',
        ]);

        if ($request->hasFile('thumbnail')) {
            if ($sourceCode->thumbnail) {
                Storage::disk('public')->delete($sourceCode->thumbnail);
            }
            $validated['thumbnail'] = $request->file('thumbnail')->store('source-codes/thumbnails', 'public');
        }

        // Convert technologies string to array
        if (!empty($validated['technologies'])) {
            $validated['technologies'] = array_map('trim', explode(',', $validated['technologies']));
        } else {
            $validated['technologies'] = [];
        }

        $sourceCode->update($validated);

        return redirect()->route('instructor.source-codes.show', $sourceCode->id)
            ->with('success', 'Source code berhasil diperbarui!');
    }

    public function destroy($id)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can delete all source codes, instructor only deletes their own
        $query = $user->isAdmin()
            ? SourceCode::query()
            : SourceCode::where('instructor_id', $userId);
        
        $sourceCode = $query->findOrFail($id);
        
        if ($sourceCode->thumbnail) {
            Storage::disk('public')->delete($sourceCode->thumbnail);
        }
        
        $sourceCode->delete();

        return redirect()->route('instructor.source-codes.index')
            ->with('success', 'Source code berhasil dihapus!');
    }

    public function publish($id)
    {
        $userId = Auth::id();
        $user = Auth::user();
        
        // Admin can publish all source codes, instructor only publishes their own
        $query = $user->isAdmin()
            ? SourceCode::query()
            : SourceCode::where('instructor_id', $userId);
        
        $sourceCode = $query->findOrFail($id);
        
        // Toggle publish status
        $sourceCode->update(['is_published' => !$sourceCode->is_published]);
        
        $status = $sourceCode->is_published ? 'dipublikasikan' : 'disembunyikan';
        
        return redirect()->back()
            ->with('success', "Source code berhasil {$status}!");
    }
}
